apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: dpsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      nodeSelector:
        DPSRV_REGION: cnt-use1
      enableServiceLinks: false
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:2.70.1
          ports:
            - containerPort: 5540
          env:
            - name: DEBUG
              value: "*,-follow-redirects*"
            - name: RI_REDIS_ALIAS
              value: dpsrv
            - name: RI_REDIS_HOST
              value: redis-0.redis.dpsrv.svc.cluster.local
            - name: RI_REDIS_PORT
              value: '6379'
            - name: RI_DATABASE_MANAGEMENT
              value: 'false'
            - name: RI_LOG_LEVEL
              value: debug
            - name: RI_FILES_LOGGER
              value: 'false'
            - name: RI_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-ri-redis-password 
                  key: redis-ri-redis-password 

          #resources:
            #requests:
              #cpu: "100m"
              #memory: "256Mi"
            #limits:
              #cpu: "500m"
              #memory: "512Mi"

